name: Python Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Linting
        run: poetry run flake8 . --show-source --max-complexity=10 --max-line-length=120 --statistics
      - name: Test with pytest
        run: poetry run pytest
